[package]
name = "Mersenne"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
tokio = { version = "1", features = ["full"] }
rayon = "1.10.0"
structopt = "0.3.26"